### ISSUE TITLE
Binary search is implemented incorrectly

### ISSUE THREAD

**Issue by n-ext** [Karlheinzniebuhr/the-weather-scraper#10]
Binary search to find first data isn't implemented correctly. For example consider date range: 01.01.2019 - 01.01.2020 when both dates have data in table. In this situation expected first date is 01.01.2019 (after single check) but current implementation leads to first date not found.

**Comment by Karlheinzniebuhr** [comment]
Thanks for reporting, I don't have time to work on this but feel free to send me a pull request with the fix.
