### ISSUE TITLE
Even when data exist program can't found them 

### ISSUE THREAD

**Issue by kamkamkil** [Karlheinzniebuhr/the-weather-scraper#2]
for example 
https://www.wunderground.com/dashboard/pws/IWARSA68/graph/2000-01-8/2000-01-8/daily
there is data for 2000-01-8 but i still get 0 row found

**Comment by Karlheinzniebuhr** [comment]
Hi, it looks at the table marked in red, and as you can see in my screenshot, there is no data from the 2000's. The station seems to be pretty new, as I find data only fairly recently (second screenshot)
![imagen](https://user-images.githubusercontent.com/5278928/104052203-1e624d80-51c8-11eb-9912-6106ec53e5b0.png)

![imagen](https://user-images.githubusercontent.com/5278928/104052334-52d60980-51c8-11eb-836c-bef0f7a029d4.png)

**Comment by kamkamkil** [comment]
i noticed it it seems like for older time they only have summary thanks for quick reply
