### ISSUE TITLE
No data output

### ISSUE THREAD

**Issue by frankboettcher** [Karlheinzniebuhr/the-weather-scraper#3]
When I start the script, I only get:
https://www.wunderground.com/dashboard/pws/IMUNIC30
getting 🌞 🌨 ⛈ from https://www.wunderground.com/dashboard/pws/IMUNIC30/table/2021-01-01/2021-01-01/daily

Then nothing more happens until I stop the script. 
The file IMUNIC30.csv only contains the headers. 
Any ideas how to debug?

**Comment by Karlheinzniebuhr** [comment]
Just updated the xpath, the html structure changed. Seems to be working now, can you please try again?

**Comment by frankboettcher** [comment]
Thank you for your quick fix! 
Now it is partly working. 

After downloading several months of data correctly I get the message:

getting 🌞 🌨 ⛈ from https://www.wunderground.com/dashboard/pws/IMUNIC70/table/2021-04-04/2021-04-04/daily
didn't find the data table, xpath update might be needed
didn't find the data table, xpath update might be needed
didn't find the data table, xpath update might be needed
didn't find the data table, xpath update might be needed
didn't find the data table, xpath update might be needed


Any ideas?

**Comment by Karlheinzniebuhr** [comment]
I managed to download your station feel free to download [here](https://drive.google.com/file/d/116mRCIvXlcMvCqYYI7WlNg7Ub8AT9Ikf/view?usp=sharing)
I'm trying to update the session each time that error occurs. If it fixes the problem I'll push the change

**Comment by Karlheinzniebuhr** [comment]
With this latest version, I managed to download the entire station several times successfully now

**Comment by frankboettcher** [comment]
Thank‘s! Now everything is working fine!
