### ISSUE TITLE
Printing emoji/icon characters causes charmap error

### ISSUE THREAD

**Issue by nabelekt** [Karlheinzniebuhr/the-weather-scraper#6]
https://github.com/Karlheinzniebuhr/the-weather-scraper/blob/4850017c0f2568943bfc05662bd6af04c6936bb1/weather_scraper.py#L63

At least on Windows, this line is causing this error:
`'charmap' codec can't encode character '\U0001f31e' in position 0: character maps to <undefined>`

```
$ python3 --version
Python 3.10.2
```

Thanks for sharing your work on this!

**Comment by Karlheinzniebuhr** [comment]
Thanks, solved this issue by deleting those icons. Please pull the new version
