### ISSUE TITLE
Timezone information

### ISSUE THREAD

**Issue by nabelekt** [Karlheinzniebuhr/the-weather-scraper#7]
Do you know if the data from WU includes timezone/dst information? I don't see it in
`data_rows = Parser.parse_html_table(date_string, history_table)`, so guessing not, but this would be very useful.

**Comment by Karlheinzniebuhr** [comment]
There is no additional timezone information, just the data you see in the table. Timezone by default is the timezone of that station. So to convert to UTC for example, you'd have to do that yourself
![image](https://user-images.githubusercontent.com/5278928/158060444-9187aa9f-b7e5-485b-9a30-caf80d7abdc4.png)

**Comment by nabelekt** [comment]
Acknowledged. I am assigning the timezone and then converting to UTC myself. Was just hoping that I wouldn't need to specify the starting timezone. Thanks!
